[package]
name = "riptide-shell"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide programming language interpreter"
edition = "2018"

[dependencies]
atty = "0.2"
clipboard = "0.5"
directories = "3.0"
exitcode = "1.1"
flume = "0.10"
futures = "0.3"
lazy_static = "1"
scopeguard = "1.1"
structopt = "0.3"
syslog = "5"
toml = "0.5"
yansi = "0.5"

[dependencies.log]
version = "0.4"
features = ["std"]

[dependencies.log-panics]
version = "2.0"
features = ["with-backtrace"]

[dependencies.riptide-runtime]
path = "../runtime"

[dependencies.riptide-stdlib]
path = "../stdlib"

[dependencies.rusqlite]
version = "0.28"
features = ["bundled"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1.2"
features = [
    "io-util",
    "process",
    "rt",
    "signal",
]

[target.'cfg(unix)'.dependencies]
termios = "0.3"
vte = "0.10" # parsing user input
