[package]
name = "riptide-testing"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "Riptide testing helpers"

[dependencies]
lazy_static = "1"
regex = "1.0"
xmltree = "0.8"
