= Riptide Language Reference

== Introduction

This manual is the primary reference for the Riptide programming language and defines its core syntax and semantics. IThe intended audience is for developers working on the language itself and for curious users who wish to dig deeper into the language. This document is not a complete formal specification at this time.


== Syntax

Riptide has a very small syntax with only a few rules and only a few forms. This makes Riptide easy to learn, and also allows the Riptide interpreter to be really small and fast.


=== Lines and whitespace

Horizontal whitespace has no meaning, except when used as a separator. When whitespace is used to separate syntactic elements, any one or more combination of horizontal whitespace counts as one separator.

Line separators are treated just like horizontal whitespace, except inside blocks.


=== Formal grammar

Below is the full specification of the Riptide grammar (in an extended Backus–Naur form):

----
Program                 = StatementList
StatementList           = (Statement StatementSeparator)* Statement?
StatementSeparator      = LineTerminator+ | ';'
Statement               = Pipeline
Pipeline                = FunctionCall (Pipe FunctionCall)*
FunctionCall            = Expr (Whitespace Expr)*
Expr                    = BlockExpr | '(' FunctionCall ')' | String
BlockExpr               = BlockParams? '{' StatementList '}'
BlockParams             = '[' (Whitespace BareString)* Whitespace? ']'
String                  = BareString | SingleQuotedString | DoubleQuotedString
BareString              = [a-Z0-9_]+
SingleQuotedString      = "'" [^']* "'"
DoubleQuotedString      = '"' [^"]* '"'
Variable                = '$' [a-Z] [a-Z0-9_]*
Pipe                    = '|'
Whitespace              = WhitespaceChar+
LineTerminator          = '\r\n' | '\n'
CharEscapeSequence      = '\' '\'
WhitespaceChar          = '\x20' | '\x09' | '\x0a' | '\x0d'
----


== Expressions

Riptide is an expression based language, where nearly every construct is an expression. All expression types are legal in the same places.

Every expression has a resulting value when it is executed.


=== Literal expressions

A _literal expression_ consists of a single literal value.

The resulting value for a literal expression is always the the literal value written.


=== Pipeline expressions


=== Block expressions

A _block expression_ defines a new _block_.


== Lexical scope and variables

Variables must be explicitly declared before they are used. By default, a variable is confined to the lexical scope in which it is defined.


=== Function calls


=== Pipelines


=== Blocks

A _block_ is a special section of code whose execution is deferred until at a later point in a program. A block is also a means of executing multiple statements in sequential order.

A block is defined using curly braces (`{` and `}`) and includes all code between the opening and closing braces.

----
{
    println "I am in a block."
}
----

Inside a block is a list of _statements_, which are each pipelines to be executed. Statements may be separated by newlines or optionally by the _statement terminator_, a single semicolon (`;`). Both separators are equivalent.

----
{
    println "Statement one."
    println "Statement two."; println "Statement three."
}
----


== Data types

Riptide has a simple data model and only offers a few basic data types.


=== Strings

The string is the most fundamental data type in Riptide. A _string_ is a fixed-length array of bytes. Usually it contains text encoded using the UTF-8 encoding, but non-text strings are also valid.

String are immutable values; functions that combine or modify text return new strings rather than modify existing strings.

Since strings are immutable, it is implementation-defined as to whether strings are passed by value or by reference, as it makes no difference in program behavior.

Strings can be created without quotes, single quotes (`'`), or double quotes (`"`), each with a slightly different meaning.


=== Numbers

Only one number type os offered. All numbers are double-precision floating-point numbers.

Numbers are immutable values.


=== Lists

Lists are the first _compound_ data type, or a container type that can hold multiple other data items. A _list_ is a fixed-length array containing zero or more values in sequence. The contained values can be of any data type.

Lists are immutable values, and cannot be modified once they are created.

It is implementation-defined as to whether lists are passed by value or by reference, as it makes no difference in program behavior.


=== Tables

A table (or associative array) is a collection of key-value pairs, where each key appears at most once in the collection.

Unlike other data types, tables are _mutable_ and can be modified in place.

Tables are passed by reference instead of by value.

The storage representation of a table is implementation-defined.


== Execution model

=== Local variables

Local variables are _lexically scoped_ bindings of names to values, and only exist inside the function they are defined in.

Local variables are mutable in the sense that they can be redefined at any time.


=== Context variables

In contrast with local variables, which are lexically scoped, _context variables_ are a form of global variables that offers _dynamic scoping_.


=== Binding resolution


=== Exceptions

As is common in many languages, exceptions offer a means of breaking out of regular control flow when runtime errors are encountered or other exceptional situations arise.

When the Riptide runtime encounters a _recoverable_ error, it _raises_ an exception that describes the error that occurred.

NOTE: Not all errors in the runtime get turned into exceptions. If an error occurs that the runtime cannot safely recover from, such as running out of memory or data corruption, the program will be aborted instead.

Riptide programs are also free to raise their own exceptions at any time during program execution using the `raise` builtin function.

Regardless of the origin of the exception, when an exception is raised, the current function call is aborted recursively in a process called _stack unwinding_, until the exception is caught. A raised exception may be caught by the first `try` block encountered that wraps the offending code.

If a raised exception is not caught during stack unwinding before the top of the stack is reached, then the runtime will attempt to print a stack trace of the exception if possible, then abort the program.


== External commands

External commands can be executed in the same way as functions are, and use the same function call mechanism.

Native data types passed to a command as arguments are _coalesced_ into strings and then passed in as program arguments. The function call waits for the command to finish, then returns the exit code of the command as a number.


== Platform interaction

=== Environment variables

Process environment variables are exposed to a Riptide program via a `environment` context variable. This variable is populated with a map of all of the current process environment variables when the runtime is initialized.

The `environment` map is not linked to the process environment map after initialization; modifying the contents of the map at runtime does not update the current process's environment. Whenever a subprocess is spawned, the subprocess's environment is created by exporting the current value of `environment`. This mimics normal environment variable support without the normal overhead required, and offers the benefits of being a regular context variable.


=== Processes

As process parallelism and external commands are essential features of Riptide, defining how Riptide manages external and child processes is paramount.

The runtime acts as a form of process supervisor, and keeps track of all child processes owned by the current process. This removes much of the burden of managing processes from the programmer.

New child processes can be created in one of two ways:

* The `spawn` builtin, which creates a new child process and executes a user-supplied block inside it in parallel with the current process.
* Calling external commands, which executes the command in a child process.

In both of these cases, newly created processes have their process IDs recorded in the global _process table_, which maintains a list of all child processes the runtime is aware of.

On Unix-like systems, when the process


=== Input and output

==== Pipes


== Module system


== Standard library

This section of the reference describes all of the built-in functions that must be provided by the Riptide runtime for any program.


=== Core functions

==== `def`

Define a new variable.


==== `builtin`

Call the builtin function with the given name and arguments.


==== `command`

Execute an external command as a function.


==== `help`

Print out user help for using Riptide.


=== Input and output

==== `print`

Writes each argument given to standard output.


==== `println`

Writes each argument given to standard output, with a trailing newline separator.


==== `echo`

An alias for `println`.


==== `eprint`

Writes each argument given to standard error.


==== `eprintln`

Writes each argument given to standard error, with a trailing newline separator.


=== Working with strings

==== `str?`

Check if the given values are strings.


==== `str:format`


==== `str:match`

Applies a regular expression to a string and emits matches and captures.


==== `str:replace`

Applies a regular expression to a string and replaces matches with the received values.


=== Tables

==== `table-get`

==== `table-set`


=== Stream functions

==== `send`

Sends one or more values to the current output channel.


==== `recv`

Receives a value from the input channel.


=== Process management

==== `pid`

Returns the PID of the current process.


==== `exit`

Terminate the current process, with an optional status code.

NOTE: By default, all child processes will also be terminated in as safe a manner as possible before the current process exits. Child processes that do not respond will be terminated forcefully. To bypass this behavior, pass the `--orphan` flag.


==== `spawn`

Spawn a new process and execute a given block within it. Returns the PID of the new process.

Calling `spawn` will never interrupt the current fiber; the spawned fiber will not be started until at least the current fiber yields.


==== `kill`

Send an interrupt or signal to a running process.


==== `sleep`

Suspend the current process for a given amount of time.


==== `exec`

Execute a command, replacing the current process with the executed process.

NOTE: Like `exit`, `exec` will do its best to clean up the current process as safely as possible before replacing the current process.

WARNING: This replaces the current _process_, which includes all fibers in the current process.


=== Exceptions

==== `throw`

Throw an exception.


==== `catch`

Execute a block, and if the block throws an exception, return the thrown exception.


=== Other functions

* `=`
* `!`
* `+`
* `-`
* `|`
* `>`
* `<`
* `cd`
* `apply`
* `or`
* `and`
* `env`
* `if`
* `list`
* `nth`
* `pwd`
* `read`
* `write`
* `each`
* `source`
* `slice`
* `count`
* `type`
* `tostring`
* `toint`
* `concat`
* `split`
* `filter`
* `random`
* `parse`
* `first-where`
* `last-where`
* `reduce`
* `fold`
* `join`
* `contains`
* `for-each`
* `every`
* `any`
* `collect`
* `pipe`


==== `lines`

Calls a function on each line of input read.

----
ls -l | lines {
    println $6
}
----
