name: publish docs
on:
  push:
    branches:
      - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker://asciidoctor/docker-asciidoctor
        with:
          args: make docs

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs
